# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  # deployment in development mode 
  build:
    docker:
      - image: circleci/node:latest-browsers # basically tells Circle to use Node.js docker runner to deploy the app to Now on every push
    working_directory: ~/repo
    steps: # A list of steps to be performed
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install
      - run: sudo yarn global add now --no-save  # Install Now CLI on GitLab CI
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: now -p -t $NOW_TOKEN


  deploy-production:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/repo
    steps:
      - checkout
    - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
    - run: now -p -t $NOW_TOKEN && now alias -t $NOW_TOKEN
    - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
    version: 2
    unscheduled:
      jobs:
        - build
        - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - /feature-.*/
        - deploy-production:
          requires:
            - build
          filters:
            branches:
              only: master