version: 2 # This indicates the version in which Circle works
jobs:
  build:
    docker:
    # specify the version you desire here
    # basically tells Circle to use Node.js docker runner to deploy the app to Now on every push
      - image: circleci/node: latest-browsers

    working_directory: ~/repo
    
    steps:
      - checkout
      - run: npm install
      - run: npm install now --no-save # Install Now CLI on Travis